version: '3.1'

services:

  reverse-proxy:
    image: osirixfoundation/elasticsearch-reverse-proxy:latest
    container_name: reverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
      - pwd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Zurich:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - KHEOPS_ROOT_SCHEME=https
      - KHEOPS_ROOT_HOST=medirad-kibana.kheops.online
    depends_on:
      - elasticsearch
      - kibana
    extra_hosts:
      - "medirad-kibana.kheops.online:127.0.0.1"
    restart: on-failure 
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    volumes:
      - /home/ansible/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    restart: on-failure 

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes: 
      - /home/ansible/elasticsearch/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx3g 
    restart: on-failure      
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - /home/ansible/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure 

  
volumes:
  esdata01:
    driver: local
      
      
secrets:
  privkey1.pem:
    file: privkey1.pem
  fullchain1.pem:
    file: fullchain1.pem
  pwd:
    file: pwd
