version: '3.1'

services:

  reverse-proxy:
    image: osirixfoundation/elasticsearch-reverse-proxy:certbot
    container_name: reverseproxy
    secrets:
      - pwd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Zurich:/etc/timezone:ro
      - ./letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - KHEOPS_ROOT_SCHEME=https
      - KHEOPS_ROOT_HOST=kibana2.kheops.online
      - KHEOPS_ROOT_URL=https://kibana2.kheops.online
    depends_on:
      - elasticsearch
      - kibana
    extra_hosts:
      - "kibana2.kheops.online:127.0.0.1"
    restart: on-failure
    networks:
      - kibana_network
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    container_name: kibana
    volumes:
      - /home/ansible/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    restart: on-failure
    networks:
      - kibana_network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx3g      
    restart: on-failure   
    networks:
      - kibana_network

  elasticsearch:
    image: my_elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /medirad8_archive:/backup
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: on-failure
    networks:
      - kibana_network

#  elastalert:
#    image: bitsensor/elastalert:3.0.0-beta.0
#    container_name: elastalert
#    volumes:
#      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
#      - ./elastalert/config/elastalert-test.yaml:/opt/elastalert/config-test.yaml
#      - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json
#      - ./elastalert/rules:/opt/elastalert/rules
#      - ./elastalert/rule_templates:/opt/elastalert/rule_templates
#    ports:
#      - "3030:3030"
#      - "3333:3333"
#    depends_on:
#      - elasticsearch
#      - kibana
  
volumes:
  esdata01:
    driver: local
    
networks:
  kibana_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.241.0/24"  
      
secrets:
  pwd:
    file: pwd
