version: '3.1'

services:

  reverse-proxy:
    image: osirixfoundation/elasticsearch-reverse-proxy:unsecure
    container_name: reverseproxy
    secrets:
      - pwd
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Zurich:/etc/timezone:ro
    ports:
      - "8081:80"
    environment:
      - NGINX_ROOT_SCHEME=https
      - NGINX_ROOT_HOST=kibana.kheops.online
    depends_on:
      - elasticsearch
      - kibana
    extra_hosts:
      - "kibana.kheops.online:127.0.0.1"
    networks:
      - kibana_network
    restart: always
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.0
    container_name: kibana
    volumes:
      - /home/ansible/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    environment:
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    restart: on-failure
    networks:
      - kibana_network
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.0
    container_name: logstash
    ports:
      - "5044:5044"
    volumes: 
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    environment:
      - LS_JAVA_OPTS=-Xmx3g     
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    restart: always   
    networks:
      - kibana_network

  elasticsearch:
    image: my_elasticsearch:7.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /medirad15_archive:/backup
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - kibana_network

  elastalert:
    image: bitsensor/elastalert:3.0.0-beta.1
    container_name: elastalert
    volumes:
      - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml
      - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json
      - ./elastalert/rules:/opt/elastalert/rules
    ports:
      - "3030:3030"
      - "3333:3333"
    environment:
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
    depends_on:
      - elasticsearch
      - kibana
    networks:
      - kibana_network
    restart: always
  
volumes:
  esdata01:
    driver: local
    
networks:
  kibana_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.241.0/24"  
      
secrets:
  pwd:
    file: pwd
