version: '3.1'

services:

  reverse-proxy:
    image: osirixfoundation/elasticsearch-reverse-proxy:latest
    container_name: reverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Zurich:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
    environment:
      - KHEOPS_ROOT_SCHEME=https
      - KHEOPS_ROOT_HOST=kibana.kheops.online
    depends_on:
      - elasticsearch
      - kibana
    extra_hosts:
      - "kibana.kheops.online:127.0.0.1"
  
  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:0.8.0
    container_name: kibana
    volumes:
      - /home/ansible/elasticsearch/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"

   
  elasticsearch:
    image: amazon/opendistro-for-elasticsearch:0.8.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - /home/ansible/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
      
volumes:
  esdata01:
    driver: local
      
      
secrets:
  privkey1.pem:
    file: privkey1.pem
  fullchain1.pem:
    file: fullchain1.pem
