version: '3.1'

services:

  reverse-proxy:
    image: osirixfoundation/elasticsearch-reverse-proxy:latest
    container_name: reverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo/Europe/Zurich:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - elasticsearch
      - kibana
    extra_hosts:
      - "kibana.kheops.online:127.0.0.1"
  
  kibana:
    image: kibana:6.6.2
    container_name: kibana
   
  elasticsearch:
    image: elasticsearch:6.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
   
      
      
      
      
secrets:
  privkey1.pem:
    file: privkey1.pem
  fullchain1.pem:
    file: fullchain1.pem
